export const PERMISSIONS = {
  VIEW_OWN_PTO: "VIEW_OWN_PTO",
  REQUEST_PTO: "REQUEST_PTO",
  VIEW_TEAM_PTO: "VIEW_TEAM_PTO",
  MANAGE_PTO_REQUESTS: "MANAGE_PTO_REQUESTS",
  EXPORT_PTO_DATA: "EXPORT_PTO_DATA",
  VIEW_SYSTEM_LOGS: "VIEW_SYSTEM_LOGS",
  MANAGE_ORGANIZATION: "MANAGE_ORGANIZATION",
};

export const PERMISSIONS_LIST = Object.values(PERMISSIONS);

export const PERMISSION_DESCRIPTIONS = {
  VIEW_OWN_PTO: "View your own PTO balance and history",
  REQUEST_PTO: "Submit and manage your own PTO requests",
  VIEW_TEAM_PTO: "View PTO information for all team members",
  MANAGE_PTO_REQUESTS: "Approve or deny PTO requests from team members",
  EXPORT_PTO_DATA: "Download PTO reports and analytics",
  VIEW_SYSTEM_LOGS: "Access system activity and audit logs",
  MANAGE_ORGANIZATION: "Full administrative control over organization settings",
};

export const PERMISSIONS_NEW = {
  // Organization Management
  MANAGE_ORGANIZATION: "MANAGE_ORGANIZATION",
  MANAGE_BILLING: "MANAGE_BILLING",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",

  // User & Role Management
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  INVITE_USERS: "INVITE_USERS",

  // Policy Management
  MANAGE_POLICIES: "MANAGE_POLICIES",
  VIEW_ALL_POLICIES: "VIEW_ALL_POLICIES",
  MANAGE_DEPARTMENT_POLICIES: "MANAGE_DEPARTMENT_POLICIES",

  // PTO Management
  VIEW_OWN_PTO: "VIEW_OWN_PTO",
  REQUEST_PTO: "REQUEST_PTO",
  VIEW_TEAM_PTO: "VIEW_TEAM_PTO",
  VIEW_DEPARTMENT_PTO: "VIEW_DEPARTMENT_PTO",
  VIEW_ALL_PTO: "VIEW_ALL_PTO",
  MANAGE_PTO_REQUESTS: "MANAGE_PTO_REQUESTS",

  // Reporting & Analytics
  EXPORT_PTO_DATA: "EXPORT_PTO_DATA",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  VIEW_SYSTEM_LOGS: "VIEW_SYSTEM_LOGS",

  // Department Management
  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",
  VIEW_DEPARTMENT: "VIEW_DEPARTMENT",
};
