export const PERMISSIONS = {
  VIEW_OWN_PTO: "VIEW_OWN_PTO",
  REQUEST_PTO: "REQUEST_PTO",
  VIEW_TEAM_PTO: "VIEW_TEAM_PTO",
  MANAGE_PTO_REQUESTS: "MANAGE_PTO_REQUESTS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  EXPORT_PTO_DATA: "EXPORT_PTO_DATA",
  VIEW_SYSTEM_LOGS: "VIEW_SYSTEM_LOGS",
  MANAGE_POLICIES: "MANAGE_POLICIES",
  MANAGE_ORGANIZATION: "MANAGE_ORGANIZATION",
};
